sudo: required
dist: trusty
language: python
python:
- '2.7'
install:
- mkdir ../data
- mkdir ../data/db
- mkdir ../data/media
- pip install -r requirements.txt
script: python -m unittest discover tests
cache:
  directories:
  - "$HOME/.cache/pip"
